### ISSUE TITLE
[Bug] 'Image Zoom' option interferes with native Obsidian variant on mobile

### ISSUE THREAD

**Issue by Jnosh** [SlRvb/Obsidian--ITS-Theme#173]
### Describe the bug
The mobile version of Obsidian has a built-in equivalent to the ITS 'Image Zoom' option. Unfortunately, if 'Image Zoom' is enabled in the ITS settings (to use it with the desktop version) it interferes with the built-in version and neither works right.

The easiest solution is probably to just only enable 'Image Zoom' on the desktop client since it isn't really needed on mobile anyway.

### To Reproduce
* Enable 'Image Zoom' in ITS settings
* Add an image embed
* Tap on the embedded image on Obsidian Mobile

### OS
* Obsidian 1.1.9 on macOS 13.2
* Obsidian Mobile 1.4.1 on iPad OS 16.3

### Additional context

I am currently working round the issue by disabling 'Image Zoom' and creating a snippet with the image zoom CSS that is only enabled on desktop. Something similar should probably work for ITS proper.

```css
body:not(.is-mobile) .markdown-preview-view img {
  cursor: zoom-in;
}

body:not(.is-mobile) .markdown-preview-view img:active {
  cursor: zoom-out;
  display: block;
  z-index: 100;
  position: fixed;
  max-height: 100%;
  max-width: 100%;
  height: 100%;
  width: 100%;
  object-fit: contain;
  margin: 0 auto;
  text-align: center;
  top: 50%;
  transform: translateY(-50%);
  padding: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```
