### ISSUE TITLE
[FR] Disable checkbox changes for alternate checkboxes

### ISSUE THREAD

**Issue by matthewturk** [SlRvb/Obsidian--ITS-Theme#228]
### Is your feature request related to a problem? Please describe.

I occasionally will accidentally click a checkbox that I've used something like `[d]` or other alternate checkbox icon in.

### Describe the solution you'd like

I think it should be possible to disable checking them.  Looking at how snippetor does it, it supplies these CSS attributes:

```
pointer-events: none;
cursor: not-allowed;
```

to any `input[type=checkbox]:checked` that matches `[data-task=]` where data-task is the custom checkbox.

### Describe alternatives you've considered

I've tried doing this myself with snippets, but I couldn't get them to propagate.

**Comment by matthewturk** [comment]
Actually, I was able to do this with a CSS snippet, and so I'll go ahead and close this.

```scss
/* @settings

name: Disable Alternate Checkbox Clicking
id: disable-alt-checkbox-clicking
settings:
    - 
        title: Disable Checkbox Clicking
        description: Disable clicking on checkboxes
        id: check-click
        type: class-toggle

*/

.check-click {
    .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task]:not([data-task=" "],[data-task="x"]),
    :is(ul, ol) > li[data-task]:not([data-task=" "],[data-task="x"]).task-list-item.is-checked
    {pointer-events: none;}
}
```
