### ISSUE TITLE
[Bug] The height of the top bar changes without reason

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#230]
### Describe the bug

Normal state after several restarts:

![Snipaste_2023-07-24_09-08-14](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/30563826/1e57bccf-25a7-4b21-8540-525f8edd5b6e)

At this time, there is a certain distance between the tab and the top, and the height of the minimize, maximize, and close buttons is also consistent with the top bar

Once a new tab is added or the tab is switched, the top bar will be several px shorter,

![Snipaste_2023-07-24_09-08-39](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/30563826/e2349a0e-cc54-4ae3-8711-aa17201ca195)

Minimize, maximize, close buttons also exceed the height of the top bar,

![Snipaste_2023-07-24_09-09-00](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/30563826/cda36f12-41c1-4a47-a45b-9dff4056e1d4)

The tab style in the picture is changed by myself, but even if all the custom css is cancelled, there are still related phenomena, hope to fix it

css written by myself:
```css
.mod-root .workspace-tab-header-container-inner {
    margin-top: 2px;
}

.workspace-tab-header:hover {
    background-color: var(--accent);
}

.workspace .mod-root .workspace-tab-header {
    border: 0.12em solid var(--inactive);
    box-shadow: 3px 3px var(--outline);
    height: 85%;
}

.workspace .mod-root .workspace-tab-header.is-active {
    border: 0.18em solid var(--interactive-accent);
}

.workspace .mod-root .workspace-tab-header:not(:last-child) {
    margin-right: 3px;
}
```

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: latest
- ITS Theme Version: latest
