### ISSUE TITLE
[Bug] text-small callout adjustment doesn't work

### ISSUE THREAD

**Issue by miscoined** [SlRvb/Obsidian--ITS-Theme#247]
### Describe the bug
The `text-small` callout adjustment doesn't work - the font size is the same as when the adjustment is not applied. Other callout adjustments (eg text-center) work fine. It also seems to not work regardless of what type of callout it is. It's the same in live preview and reading mode.

**Expected behavior**
The text should be smaller, as per [Callout Adjustments](https://publish.obsidian.md/slrvb-docs/ITS+Theme/Callout+Adjustments#Adjustments)

### To Reproduce

1. Add the following to a note in a new vault with ITS theme installed
```
> [!note|text-small] Small text
> This text should be small

> [!note] Normal text
> This text should be the normal size
```
2. Observe in live preview and reading mode that the text is the same size in both callouts

### Screenshots
![Screenshot_2023-09-16_17-12-41](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/10219544/536e50ec-d781-41df-9cdb-a32c2eebe5a2)

### OS
Where does the bug occur?

- [x] Desktop
- [?] Mobile

### Versions
- Obsidian Version: 1.4.13
- ITS Theme Version: 1.1.20

### Additional context
I had a look at the inspector and I can see these (in this order, and according to the inspector they're not being overriden by anything).
```css
/* inherited from div.callout.drop-shadow */
.callout.callout:is([data-callout-metadata~=text-small],
[data-callout-metadata~=txt-s]) {
    --font-text-size: var(--font-smallest);
    --tag-size: var(--font-smallest);
    --table-text-size: var(--font-smallest);
}

/* inherited from .markdown-source-view */
.markdown-source-view {
    font-size: var(--font-text-size);
    font-family: var(--font-text);
}
```

Adding a new rule in the inspector like so fixes the issue:
```css
p {
  font-size: var(--font-text-size);
}
```

I think this is actually the same problem that's talked about in [this StackOverflow question](https://stackoverflow.com/questions/52015737/css-scoped-custom-property-ignored-when-used-to-calculate-variable-in-outer-scop/52015817#52015817). `--font-text-size` is being *used* at the `.markdown-source-view` level, but it's being *set* at a descendant element of that so it doesn't actually have the new value at `.markdown-source-view` level where it's actually used.

Thank you for all your work on this excellent theme!
