### ISSUE TITLE
Search highlight in Preview not clear in Light

### ISSUE THREAD

**Issue by DutchPete** [SlRvb/Obsidian--ITS-Theme#3]
Cmd/Ctrl+F in Preview in Light mode highlights matching terms in the text, but the highlight is a very pale pink, hardly distinguishable.

I looked in the theme's CSS but could not work out which rules controls the color.

I have a snippet for it too, but it does not work in your theme.
```css
/* Local (= in note) search match highlight color change in Preview mode */
.markdown-preview-view .search-highlight > div {
  background-color: orange;
  color: black;
}
```

Please advise.
