### ISSUE TITLE
Admonition in Live Preview - small style fix (?)

### ISSUE THREAD

**Issue by VeroVerro** [SlRvb/Obsidian--ITS-Theme#54]
Hi, thank you for the wonderful theme! I've been playing around with it, and noticed that for admonition in live preview, it does weird things with box shadow and the edit this block button:
![Screenshot 2022-01-01 131522](https://user-images.githubusercontent.com/17042871/147850426-ef4647eb-ab0a-460d-ae09-4244f489768c.png)

I fixed it this way: (it was `contain: paint;` before)

```css
.markdown-source-view.mod-cm6 .cm-content > [contenteditable=false] {
    contain: style;
}
```

![Screenshot 2022-01-01 131709](https://user-images.githubusercontent.com/17042871/147850438-41039c15-f754-4df9-b72b-141d49942adf.png)

I haven't done a lot of testing with other types of live preview blocks though, since I haven't had time to use it much in the last week. Still, maybe it'll help. Thanks again!
