### ISSUE TITLE
Issue with emoji tags

### ISSUE THREAD

**Issue by AEnMe** [SlRvb/Obsidian--ITS-Theme#6]
**Issue:** 
When I'm using emoji as tags, the emojis are not showing correctly and are each on a new line.

- Edit mode:
`#📥`
and
`#📥/🟥 `

- View mode:
```
#
📥 
```
and
```
#
📥
/
🟥 
```

My quick fix is taking off the display line as follow, but obviously, it affects all images.

```css
/*Center Image*/
img{
/*    display: block; */
    margin-left: auto;
    margin-right: auto;
}
```

I tried different things but I'm only beginning in CSS and didn't find how to fix it.
