### ISSUE TITLE
About list bullets

### ISSUE THREAD

**Issue by zcysxy** [SlRvb/Obsidian--ITS-Theme#7]
Hi SlRvb, thank you for these great themes!

I have 2 tiny problems with list bullets. The first is that when I have ordered sub-lists, the bullets still appear and overlap with the numbers, just as the screenshot shows

![image](https://user-images.githubusercontent.com/48207708/119611382-35c76d80-be2d-11eb-803e-98507a8b26c3.png)

The second thing is that I am used to using `*` as list identifier, but seems like the diamond symbol in the editor view only fits dash `-`.

![image](https://user-images.githubusercontent.com/48207708/119612116-1aa92d80-be2e-11eb-945a-460fff099bda.png)

I found some other snippet that changes the list symbol in the editor view. Hope it would be helpful.

```css
/* list bullets */
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-list-ul {
    color: transparent;
    position: relative;
}
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-list-ul:after {
    content: "•";
    position: absolute;
    top: -5px;
    left: 0px;
    color: var(--text-normal);
    font-family: sans-serif;
    font-size: 20px;
}
```
